### ISSUE TITLE
Dataset URL

### ISSUE THREAD

**Issue by OrientKing** [liuxindazz/PDD271#1]
The URL of PDD271 dataset provided in the project has been invalid. Could you provide a new URL for downloading？

**Comment by liuxindazz** [comment]
> 
> 
> The URL of PDD271 dataset provided in the project has been invalid. Could you provide a new URL for downloading？

Due to company policy restrictions, we can only provide a small number of samples of the dataset. I updated the link.  Hope this helps.

**Comment by Lancelot365** [comment]
WIll you provide pre-trained models based on the dataset?

**Comment by liuxindazz** [comment]
Yes, we are waiting for the company's approval.

**Comment by mrmenand** [comment]
Can you provide a pretrained model or a complete dataset? You know, it's important for research

**Comment by Mr-TalhaIlyas** [comment]
hi liuxindazz,

can you please provide the dataset link?
